SportStore.Web/Components/CartSummaryViewComponent.cs
namespace SportStore.Web.Components
{
    using Microsoft.AspNetCore.Mvc;

    using SportStore.Web.Models;

    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

SportStore.Web/Components/NavigationMenuViewComponent.cs
namespace SportStore.Web.Components
{
    using Microsoft.AspNetCore.Mvc;

    using SportStore.Web.Models;

    public class NavigationMenuViewComponent : ViewComponent
    {
        private readonly IProductRepository productRepository;

        public NavigationMenuViewComponent(IProductRepository productRepository)
        {
            this.productRepository = productRepository;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(productRepository.Categories());
        }
    }
}

SportStore.Web/Controllers/CartController.cs
namespace SportStore.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    using SportStore.Web.Models;
    using SportStore.Web.Models.ViewModels;

    public class CartController : Controller
    {
        private readonly IProductRepository productRepository;

        private readonly Cart cart;

        public CartController(IProductRepository productRepository, Cart cart)
        {
            this.productRepository = productRepository;
            this.cart = cart;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
                            {
                                Cart = cart,
                                ReturnUrl = returnUrl
                            });
        }

        public RedirectToActionResult AddToCart(int productId, string returnUrl)
        {
            ProductItem product = productRepository.GetById(productId);
            if (product != null)
            {
                cart.AddItem(product, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToActionResult RemoveFromCart(int productId,
                                                     string returnUrl)
        {
            ProductItem product = productRepository.GetById(productId);
            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

SportStore.Web/Views/Shared/ProductSummary.cshtml
@using SportStore.Web.Infrastructure
@model ProductItem
<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">
            @Model.Price.ToString("c")
        </span>
    </h3>
    <form id="@Model.ProductId" asp-action="AddToCart"
          asp-controller="Cart" method="post">
        <input type="hidden" asp-for="ProductId" />
        <input type="hidden" name="returnUrl"
               value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="lead">
            @Model.Description
            <button type="submit" class="btn btn-success btn-sm pull-right">
                Add To Cart
            </button>
        </span>
    </form>
</div>

SportStore.Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <script asp-src-include="lib/jquery/**/jquery.min.js"></script>
    <script asp-src-include="lib/jquery-validation/**/jquery.validate.min.js"></script>
    <script asp-src-include="lib/jquery-validation-unobtrusive/**/*.min.js"></script>
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error { border-color: red; background-color: #fee ; }
    </style>
</head>
<body class="panel panel-default">
<div class="panel-heading"><h4>@ViewBag.Title</h4></div>
<div class="panel-body">
    @if (TempData["message"] != null) {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    @RenderBody()
</div>
</body>
</html>

SportStore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <link rel="stylesheet" asp-href-include="/lib/font-awesome/css/*.css" />
    <title>SportsStore</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">SPORTS STORE</a>
        <div class="pull-right">
            @await Component.InvokeAsync("CartSummary")
        </div>
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>